"""Add Restaurant-Customer relationship

Revision ID: f997d675d885
Revises: af689dc5343f
Create Date: 2024-01-08 18:10:41.495164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f997d675d885'
down_revision = 'af689dc5343f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('restaurant_customers',
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_restaurant_customers_customer_id_customers')),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], name=op.f('fk_restaurant_customers_restaurant_id_restaurants')),
    sa.PrimaryKeyConstraint('restaurant_id', 'customer_id')
    )
    op.add_column('reviews', sa.Column('customer_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_reviews_restaurant_id_restaurants'), 'reviews', 'restaurants', ['restaurant_id'], ['id'])
    op.create_foreign_key(op.f('fk_reviews_customer_id_customers'), 'reviews', 'customers', ['customer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_reviews_customer_id_customers'), 'reviews', type_='foreignkey')
    op.drop_constraint(op.f('fk_reviews_restaurant_id_restaurants'), 'reviews', type_='foreignkey')
    op.drop_column('reviews', 'customer_id')
    op.drop_table('restaurant_customers')
    # ### end Alembic commands ###
